<?php 
 return array (
  'Repost' => '',
  'Cancel' => '',
  'Impact' => '',
  'Quality' => '',
  'Speed' => '',
  'Assiduity' => '',
  'Receive a reminder for the d-day' => '',
  'Enter your email address' => 'Receive a reminder for the d-day. Enter your email address',
  'Finish tutorial' => '',
  'Success!' => '',
  'wrong email' => 'Please enter validate email',
  'Ok' => '',
  'Send Invitation' => '',
  ' You can\\\'t invite too many people ' => '',
  'Cancel Invitation' => '',
  'Confirm' => '',
  'They’re watching you! A NEW psychological thriller from @kevwilliamson starring @DylanMcDermott &amp; @MaggieQ Wed 10/9c pic.twitter.com/o5v4b7M2is' => '',
  'do you want to leave the team?' => '',
  'Leave Team' => '',
  'T/H' => 't/h',
  'P' => '',
  'Do you want to join' => '',
  'fans_unit' => ' ',
  'Search' => '',
  'You can\\\'t invite too many people ' => '',
  'Maximum number of characters attained' => '',
);