<?php 
 return array (
  'Speed' => '速度',
  'Quality' => '内容',
  'Impact' => '影响力',
  'Cancel' => '取消',
  'Repost' => '转发',
  'Cancel Invitation' => '取消邀请',
  'Assiduity' => '成就值',
  'Receive a reminder for the d-day' => '',
  'Enter your email address' => '',
  'Finish tutorial' => '',
  'Success!' => '',
  'wrong email' => '',
  'Ok' => '',
  'Send Invitation' => '',
  ' You can\\\'t invite too many people ' => '',
  'Confirm' => '',
  'They’re watching you! A NEW psychological thriller from @kevwilliamson starring @DylanMcDermott &amp; @MaggieQ Wed 10/9c pic.twitter.com/o5v4b7M2is' => '',
  'do you want to leave the team?' => '',
  'Leave Team' => '',
);