<?php 
 return array (
  'Repost' => '',
  'Cancel' => '',
  'Impact' => '',
  'Quality' => '',
  'Speed' => '',
  'Assiduity' => '',
  'Receive a reminder for the d-day' => '接收开赛日期提醒',
  'Enter your email address' => '输入邮箱地址',
  'Finish tutorial' => '完成比赛教程',
  'Success!' => '',
  'wrong email' => '请输入正确的邮箱地址',
  'Ok' => '确定',
  'Send Invitation' => '发送邀请',
  ' You can\\\'t invite too many people ' => '',
  'Cancel Invitation' => '',
  'Confirm' => '',
  'They’re watching you! A NEW psychological thriller from @kevwilliamson starring @DylanMcDermott &amp; @MaggieQ Wed 10/9c pic.twitter.com/o5v4b7M2is' => '',
  'do you want to leave the team?' => '',
  'Leave Team' => '',
);