<?php 
 return array (
  'Repost' => '',
  'Cancel' => '',
  'Impact' => '',
  'Quality' => '',
  'Speed' => '',
  'Assiduity' => '',
  'Receive a reminder for the d-day' => '',
  'Enter your email address' => '',
  'Finish tutorial' => '',
  'Success!' => '',
  'wrong email' => '',
  'Ok' => '',
  'Send Invitation' => '',
  ' You can\\\'t invite too many people ' => '',
  'Cancel Invitation' => '',
  'Confirm' => '',
  'They’re watching you! A NEW psychological thriller from @kevwilliamson starring @DylanMcDermott &amp; @MaggieQ Wed 10/9c pic.twitter.com/o5v4b7M2is' => '',
  'do you want to leave the team?' => '',
  'Leave Team' => '',
);